### ISSUE TITLE
How to copy files between host and guest?

### ISSUE THREAD

**Issue by rogerskeie** [Arc-Compute/LibVF.IO#30]
Hi,

How can I copy files to and from the guest OS? I've tried copy paste, but that doesn't work.

I see shareddir in the yaml file, but I don't see any mention of it in the docs. I tried using "shareddir: ~/vm_shared" (the folder vm_shared does exist in my home folder by the way, I created it just for that purpose), but the VM refused to start when I did that.

How do I configure a shared directory?

Are there any other ways of sharing files between the guest and host? I saw something [here](https://www.spice-space.org/spice-user-manual.html#_folder_sharing), but not sure how to apply that to arcd.

**Comment by arthurrasmusson** [comment]
I'm working on a VirtIO-FS based shared directory. I don't have it working stable yet. I'll comment back here when it's done.

**Comment by arthurrasmusson** [comment]
@rogerskeie It turns out VirtIO-FS is unstable for Windows guests. I'm working on a Samba based share in feature/smb-automation. You can follow the progress on that over here:
https://github.com/Arc-Compute/LibVF.IO/tree/feature/smb-automation

Once I've merged it back to master I'll need to update documentation but the installation will likely be simpler overall in updated docs. I'll also try to remember to post back here once it's merged and documentation is updated.

**Comment by rogerskeie** [comment]
@arthurrasmusson Sounds promising :)

**Comment by arthurrasmusson** [comment]
Hi @rogerskeie. Checkout https://github.com/Arc-Compute/LibVF.IO/blob/master/example/samba.yaml

If you are an Nvidia user make sure you set the appropriate PCI device IDs contained in the other examples. You may also want to take a look at our updated install documentation and try using the `installOs: "win10"` parameter in order to automatically connect the share on the guest side.
https://arccompute.com/blog/libvfio-commodity-gpu-multiplexing/
