### ISSUE TITLE
Is Debian Supported?

### ISSUE THREAD

**Issue by unalkalkan** [Arc-Compute/LibVF.IO#44]
Is Debian 11 (Bullseye) supported? If so, should we use "Ubuntu" or "Other" when installing?

**Comment by arthurrasmusson** [comment]
Sorry to take awhile to get to this. We haven't validated base Debian yet but I'll try to fit that in on my list of things to do.

The "Ubuntu" and "Other" options can work in the case of systems which are sufficiently similar but in some cases there are small differences between distributions which do make a difference (for instance PopOS is based on Ubuntu but it uses systemd-boot rather than GRUB so there are some small changes we needed to make).

I'll try to check back in on this issue once I've been able to go through and validate the automated installation works on Debian.

**Comment by arthurrasmusson** [comment]
@unalkalkan We now support Debian. You'll need to install sudo before running the install.
https://github.com/Arc-Compute/LibVF.IO/commit/cdd41085eb329da73c595e4ec4d1c0dc6b9fa148

**Comment by unalkalkan** [comment]
Sorry I couldn't reply back. 
I'm looking at the changes and yeah i did some minor changes like those in the commit (ibrs=on for example) and it worked.

A little side note for the future reference, I actually tried it first with the latest windows ISO rather than the one specified in the documentation "Windows 10 LTSC". 
After installing the guest nvidia drivers and restarted the guest windows, it gave me black screen after windows loading and windows didn't open. I wasn't sure if it was because i was trying to install this project in Debian or something else, thats why I created the issue.

After trying possible solutions and installing with "Windows 10 LTSC" ISO, it fixed the black screen issue and everything was working great!
