### ISSUE TITLE
Alsa error after running "arcd create" command

### ISSUE THREAD

**Issue by zachpaul77** [Arc-Compute/libvf.io#5]
Kubuntu 21.10, whenever I use the "arcd create" command I get this error:

```
qemu-system-x86_64: warning: '-soundhw gus' is deprecated, please use '-device gus' instead
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `gus'
```

Everything works fine if I disable audio by adding QEMU_AUDIO_DRV=none in /etc/environment

**Comment by arthurrasmusson** [comment]
I pulled out use of `--soundhw all` in [this commit](https://github.com/Arc-Compute/libvf.io/commit/d8dac05d65b22c1f40520f3a450ea5889cf90b37) due to deprecation warnings that were being generated and also the fact that running a VM with VFIO passthrough appears conflict with usermode audio permissions in ALSA. I'll try to work on a fix for this soon using QEMU 5.1+'s Jack feature or [Scream](https://github.com/duncanthrax/scream).

I'm going to close this issue for now due to the removal of `--soundhw` until then.

If you'd like to try working on this some folks in the Discord are currently working on trying to get Jack working.
